package com.prologiccreations.traderssolution.constants.enums;

public enum District {
    DHAKA, FARIDPUR, GAZIPUR, GOPALGANJ, JAMALPUR, KISHOREGANJ, MADARIPUR, MANIKGANJ, MUNSHIGANJ, MYMENSINGH, NARAYANGANJ, NARSINGDI, NETROKONA, RAJBARI, SHARIATPUR, SHERPUR, TANGAIL, BOGRA, JOYPURHAT, NAOGAON, NATORE, NAWABGANJ, PABNA, RAJSHAHI, SIRAJGONJ, DINAJPUR, GAIBANDHA, KURIGRAM, LALMONIRHAT, NILPHAMARI, PANCHAGARH, RANGPUR, THAKURGAON, BARGUNA, BARISAL, BHOLA, JHALOKATI, PATUAKHALI, PIROJPUR, BANDARBAN, BRAHMANBARIA, CHANDPUR, CHITTAGONG, COMILLA, COXS_BAZAR, FENI, KHAGRACHARI, LAKSHMIPUR, NOAKHALI, RANGAMATI, HABIGANJ, MAULVIBAZAR, SUNAMGANJ, SYLHET, BAGERHAT, CHUADANGA, JESSORE, JHENAIDAH, KHULNA, KUSHTIA, MAGURA, MEHERPUR, NARAIL, SATKHIRA
}
